exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    ".pytest_cache",
    "build",
    "dist",
    "*.egg-info",
]

line-length=80

[lint]
select = [
    "E",
    "W",
    "F",
    "C90",
    "B",
    "I",
]
